# Generated by Django 2.1.3 on 2020-03-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200308_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisherman_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('Fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fish')),
                ('Fisherman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Retailer')),
            ],
            options={
                'verbose_name_plural': 'Fisherman Inventories',
            },
        ),
    ]
