# Generated by Django 2.1.3 on 2020-03-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fisherman_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisherman_inventory',
            name='Fisherman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fisherman'),
        ),
    ]
