# Generated by Django 2.1.3 on 2020-03-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200308_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('Fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fish')),
                ('Retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Retailer')),
            ],
        ),
    ]
